/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsLevelIdRouteImport } from './routes/levels.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelIdRoute = LevelsLevelIdRouteImport.update({
  id: '/levels/$levelId',
  path: '/levels/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/levels/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels/$levelId'
  id: '__root__' | '/' | '/levels/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsLevelIdRoute: typeof LevelsLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$levelId': {
      id: '/levels/$levelId'
      path: '/levels/$levelId'
      fullPath: '/levels/$levelId'
      preLoaderRoute: typeof LevelsLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsLevelIdRoute: LevelsLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
